<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            // Línea 1 – Equidad y Trayectorias
            ['strategic_line_id' => 1, 'name' => 'Tránsitos Seguros - Primera Infancia',           'slug' => 'transitos-seguros-primera-infancia',             'program' => '1. Acceso y Equidad Educativa',                                   'purpose' => 'Garantizar el acceso y la atención integral de niños y niñas en centros de desarrollo infantil y establecimientos educativos rurales y urbanos.',    'key_components' => 'Adecuación y dotación de espacios físicos seguros y estimulantes. Capacitación continua y especializada para docentes. Formación y acompañamiento a familias. Protocolos de seguridad y bienestar infantil.'],
            ['strategic_line_id' => 1, 'name' => 'Centros de Recursos para la Inclusión',          'slug' => 'centros-de-recursos-para-la-inclusion',           'program' => '1. Acceso y Equidad Educativa',                                   'purpose' => 'Garantizar apoyos especializados y accesibles para estudiantes con discapacidad.',                                                                  'key_components' => 'Adecuación de espacios accesibles. Dotación de TIC adaptativas y materiales braille/LSP. Banco de ayudas técnicas. Formación a docentes y familias en educación inclusiva.'],
            ['strategic_line_id' => 1, 'name' => 'Ruta de Cobertura Rural',                        'slug' => 'ruta-de-cobertura-rural',                        'program' => '1. Acceso y Equidad Educativa',                                   'purpose' => 'Llevar y mantener la oferta educativa completa en veredas.',                                                                                       'key_components' => 'Transporte escolar seguro. Aulas multigrado equipadas. Docentes itinerantes y tutorías virtuales. Modelos educativos flexibles. Alimentación escolar.'],
            ['strategic_line_id' => 1, 'name' => 'Habilidades para la Vida',                       'slug' => 'habilidades-para-la-vida',                       'program' => '1. Acceso y Equidad Educativa',                                   'purpose' => 'Desarrollar competencias socioemocionales y financieras en estudiantes.',                                                                           'key_components' => 'Módulos de proyecto de vida y orientación socio ocupacional. Educación financiera. Mentorías por egresados.'],
            ['strategic_line_id' => 1, 'name' => 'Puentes a la Educación Terciaria',               'slug' => 'puentes-a-la-educacion-terciaria',               'program' => '1. Acceso y Equidad Educativa',                                   'purpose' => 'Facilitar ingreso y permanencia en la educación superior.',                                                                                        'key_components' => 'Acompañamiento en inscripción, becas y pruebas. Alianzas con IES y ETDH. Clubes de lectura crítica y pensamiento lógico.'],
            ['strategic_line_id' => 1, 'name' => 'Acompañamiento a Familias',                      'slug' => 'acompanamiento-a-familias',                      'program' => '2. Desarrollo Personal, Familiar y Comunitario',                  'purpose' => 'Generar espacios de participación dirigidos a padres y cuidadores para fortalecer su rol educativo.',                                               'key_components' => 'Escuela de padres. Atención psicosocial y jurídica. Biblioteca de recursos físicos y digitales.'],
            ['strategic_line_id' => 1, 'name' => 'Educación en Convivencia y Ética',               'slug' => 'educacion-en-convivencia-y-etica',               'program' => '2. Desarrollo Personal, Familiar y Comunitario',                  'purpose' => 'Fortalecer relaciones y promover el manejo de conflictos y el respeto en la comunidad educativa.',                                                  'key_components' => 'Programa Aulas sin violencia. Mediadores escolares.'],
            ['strategic_line_id' => 1, 'name' => 'Voluntariado y Participación Comunitaria',       'slug' => 'voluntariado-y-participacion-comunitaria',       'program' => '2. Desarrollo Personal, Familiar y Comunitario',                  'purpose' => 'Articular escuela-comunidad para promover el compromiso social, la solidaridad y el desarrollo de competencias ciudadanas.',                        'key_components' => 'Plataforma de voluntariado estudiantil. Alianzas con privados y públicos. Jornadas de servicio social. Alfabetización.'],
            // Línea 2 – Calidad e Innovación
            ['strategic_line_id' => 2, 'name' => 'Plan de Mejora Continua',                        'slug' => 'plan-de-mejora-continua',                        'program' => '3. Calidad, Innovación y Mejora Continua',                        'purpose' => 'Monitorear logros y retroalimentar procesos para la mejora constante.',                                                                            'key_components' => 'Sistema de datos y tablero de control BI. Simulacros ICFES trimestrales. Planes de mejora por área.'],
            ['strategic_line_id' => 2, 'name' => 'Formación y Acompañamiento Docente',             'slug' => 'formacion-y-acompanamiento-docente',             'program' => '3. Calidad, Innovación y Mejora Continua',                        'purpose' => 'Desarrollar competencias docentes y bienestar del magisterio para mejorar prácticas pedagógicas.',                                                  'key_components' => 'Diagnóstico de necesidades. Ciclos de formación en competencias TIC, matemáticas, lectura, lenguaje, socioemocionales, gestión institucional, metodologías activas, bilingüismo, inclusión, evaluación formativa y bienestar. Comunidades de práctica. Mentores en aula. Reconocimientos e incentivos.'],
            ['strategic_line_id' => 2, 'name' => 'Centro de Innovación Educativa',                 'slug' => 'centro-de-innovacion-educativa',                 'program' => '3. Calidad, Innovación y Mejora Continua',                        'purpose' => 'Proveer recursos y cultura de la investigación para fomentar la innovación educativa.',                                                             'key_components' => 'Laboratorios STEAM. Repositorio de recursos educativos abiertos. Semilleros de investigación estudiantil.'],
            ['strategic_line_id' => 2, 'name' => 'Dotación Científica',                            'slug' => 'dotacion-cientifica',                            'program' => '3. Calidad, Innovación y Mejora Continua',                        'purpose' => 'Modernizar laboratorios para garantizar ambientes de aprendizaje adecuados.',                                                                      'key_components' => 'Laboratorios de química y física. Soporte técnico permanente y formación a docentes.'],
            ['strategic_line_id' => 2, 'name' => 'Plan Maestro de Infraestructura',                'slug' => 'plan-maestro-de-infraestructura',                'program' => '4. Infraestructura y Recursos Educativos para la Sostenibilidad', 'purpose' => 'Construir, adecuar y mantener plantas físicas para garantizar espacios educativos de calidad.',                                                    'key_components' => 'Diagnóstico técnico-financiero. Estándares de accesibilidad universal. Gestión de recursos con Nación y cooperación.'],
            ['strategic_line_id' => 2, 'name' => 'Dotación TIC Integral',                          'slug' => 'dotacion-tic-integral',                          'program' => '4. Infraestructura y Recursos Educativos para la Sostenibilidad', 'purpose' => 'Equipar todas las aulas con tecnología educativa para facilitar el acceso a recursos digitales y promover la innovación pedagógica.',              'key_components' => 'Kits de aula digital. Plataforma LMS municipal. Mantenimiento preventivo.'],
            ['strategic_line_id' => 2, 'name' => 'Laboratorios STEAM',                             'slug' => 'laboratorios-steam',                             'program' => '4. Infraestructura y Recursos Educativos para la Sostenibilidad', 'purpose' => 'Fortalecer ciencias y tecnología para fomentar el pensamiento crítico, la creatividad y la resolución de problemas.',                              'key_components' => 'Laboratorios fijos en sedes urbanas. Laboratorio móvil para veredas. Clubes de robótica y ciencia.'],
            ['strategic_line_id' => 2, 'name' => 'Alianzas para la Sostenibilidad',                'slug' => 'alianzas-para-la-sostenibilidad',                'program' => '4. Infraestructura y Recursos Educativos para la Sostenibilidad', 'purpose' => 'Asegurar recursos y el cuidado de la infraestructura para promover la eficiencia energética y el uso de energías renovables.',                  'key_components' => 'Convenios con empresas y ONG. Contratos de energía solar y agua lluvia. Convenios con jornada extendida.'],
            // Línea 3 – Identidad y Pertinencia
            ['strategic_line_id' => 3, 'name' => 'Cátedra Municipal y Multiculturalidad',          'slug' => 'catedra-municipal-y-multiculturalidad',          'program' => '5. Pertinencia y Contextualización Educativa',                    'purpose' => 'Integrar identidad, historia y diversidad local al currículo para fortalecer el sentido de pertenencia.',                                          'key_components' => 'Diseño curricular colaborativo. Materiales multilingües. Salidas pedagógicas al territorio.'],
            ['strategic_line_id' => 3, 'name' => 'PEI Actualizados y Currículos Contextualizados', 'slug' => 'pei-actualizados-y-curriculos-contextualizados', 'program' => '5. Pertinencia y Contextualización Educativa',                    'purpose' => 'Adaptar contenidos a realidades socioeconómicas y en consonancia con el PEM para mejorar la relevancia educativa.',                                'key_components' => 'Matrices de pertinencia. Secuencias didácticas diferenciadas. Evaluación por competencias. Sistemas institucionales de evaluación revisados y concertados.'],
            ['strategic_line_id' => 3, 'name' => 'Aprendizaje en Aulas Abiertas',                  'slug' => 'aprendizaje-en-aulas-abiertas',                  'program' => '5. Pertinencia y Contextualización Educativa',                    'purpose' => 'Potenciar el entorno como aula para favorecer aprendizajes experienciales y sostenibles.',                                                        'key_components' => 'Huertas escolares y viveros. Clases en espacios naturales. Salidas pedagógicas.'],
            ['strategic_line_id' => 3, 'name' => 'Gobiernos Escolares y Gestión Pedagógica',       'slug' => 'gobiernos-escolares-y-gestion-pedagogica',       'program' => '5. Pertinencia y Contextualización Educativa',                    'purpose' => 'Fortalecer la participación y el liderazgo escolar para una gestión democrática y participativa.',                                                'key_components' => 'Capacitación de representantes. Plan anual de participación. Observatorios estudiantiles.'],
            ['strategic_line_id' => 3, 'name' => 'Clubes de Lectura y Pensamiento Crítico',        'slug' => 'clubes-de-lectura-y-pensamiento-critico',        'program' => '5. Pertinencia y Contextualización Educativa',                    'purpose' => 'Fomentar el desarrollo del pensamiento crítico y la comprensión lectora a través de la lectura y el análisis de textos y contextos.',             'key_components' => 'Clubes de lectura temáticos (ciencia, historia, literatura). Guías de lectura y análisis crítico. Actividades de debate, discusión y producción escrita.'],
            ['strategic_line_id' => 3, 'name' => 'Proyectos Productivos Escolares y Rurales',      'slug' => 'proyectos-productivos-escolares-y-rurales',      'program' => '5. Pertinencia y Contextualización Educativa',                    'purpose' => 'Vincular aprendizaje con desarrollo sostenible para fomentar el emprendimiento y la conexión con el territorio.',                                  'key_components' => 'Huertas, piscicultura, agro-emprendimientos. Feria anual de ideas de negocio. Articulación con SENA.'],
            // Línea 4 – Gestión y Gobernanza
            ['strategic_line_id' => 4, 'name' => 'Mesa de Educación y JUME',                       'slug' => 'mesa-de-educacion-y-jume',                       'program' => '6. Gobernanza y Monitoreo del PEM',                               'purpose' => 'Consolidar la Mesa Municipal de Educación y la Junta Municipal de Educación como espacios de gobernanza participativa y toma de decisiones.',     'key_components' => 'Mesa de Educación activa. Junta Municipal de Educación (JUME). Sesiones periódicas y actas de seguimiento.'],
            ['strategic_line_id' => 4, 'name' => 'Sistema de Información y Tableros de Control',   'slug' => 'sistema-de-informacion-y-tableros-de-control',   'program' => '6. Gobernanza y Monitoreo del PEM',                               'purpose' => 'Implementar un sistema de monitoreo de indicadores del PEM actualizado semestralmente para visualizar avance de metas y alertar sobre desviaciones.', 'key_components' => 'Tablero de control BI. Informes anuales de avance. Evaluaciones externas cada tres años.'],
            ['strategic_line_id' => 4, 'name' => 'Participación Ciudadana y Rendición de Cuentas', 'slug' => 'participacion-ciudadana-y-rendicion-de-cuentas', 'program' => '6. Gobernanza y Monitoreo del PEM',                               'purpose' => 'Promover espacios de diálogo y rendición de cuentas para recoger aportes y fortalecer la apropiación social del PEM.',                            'key_components' => 'Audiencias públicas. Foros educativos. Plataforma digital de participación ciudadana.'],
            ['strategic_line_id' => 4, 'name' => 'Gestión de Recursos y Sostenibilidad Financiera','slug' => 'gestion-de-recursos-y-sostenibilidad-financiera','program' => '6. Gobernanza y Monitoreo del PEM',                               'purpose' => 'Gestionar recursos ante el gobierno nacional, departamental, cooperación internacional y sector privado para financiar los programas estratégicos.', 'key_components' => 'Proyección presupuestal. Plan plurianual de inversión. Alianzas público-privadas. Gestión ante SGP y cooperación internacional.'],
        ];

        foreach ($projects as $project) {
            DB::table('projects')->updateOrInsert(
                ['slug' => $project['slug']],
                array_merge($project, [
                    'progress'         => 0,
                    'goals_count'      => 0,
                    'goals_done_count' => 0,
                    'active'           => true,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ])
            );
        }

        $this->command->info('OK ProjectSeeder — ' . DB::table('projects')->count() . ' proyectos insertados.');
    }
}
